apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ldhan211099/node-app:1.3
        ports:
        - containerPort: 3001
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 30001
    targetPort: 3001
    nodePort: 30001
